FROM node:21-alpine AS base
WORKDIR /app
COPY package*.json ./

RUN npm install
COPY ../.next/standalone ./
COPY ../.next/static ./.next/static
RUN npm run build

FROM node:21-alpine AS production
WORKDIR /app
COPY --from=base /app /app

EXPOSE 3000
CMD ["npm", "start"]