import './globals.css'
import type { Metadata } from 'next'
import { MSWComponent } from '@/api/MSWComponent'
import { cn } from '@/lib/utils'
import ReactQueryProvider from '@/providers/ReactQueryProvider'
import ReduxProvider from '@/providers/ReduxProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background antialiased')}>
        {process.env.NEXT_PUBLIC_MSW === 'enable' ? (
          <MSWComponent>
            <ReactQueryProvider>
              <ReduxProvider>
                <div className="container">{children}</div>
              </ReduxProvider>
            </ReactQueryProvider>
          </MSWComponent>
        ) : (
          <ReactQueryProvider>
            <ReduxProvider>
              <div>{children}</div>
            </ReduxProvider>
          </ReactQueryProvider>
        )}
      </body>
    </html>
  )
}
